#ifndef MUTATED_H
#define MUTATED_H

// Auto-generated by RTP GUI Builder
// Timestamp: 855099

#define rtp_init rtp_OuWZKdLVmXAq
#define rtp_run rtp_XcRtYNkzRxqI
#define rtp_cleanup rtp_FeolTHtuNpLc
#define net_init rtp_oerSrmKEKjZv
#define net_cleanup rtp_gwKYsuYQFwGf
#define net_set_nonblocking rtp_yYdkVSTkwHBp
#define net_listen rtp_uNlrtvsWFVUw
#define net_connect rtp_CoNBobXayQkp
#define rc4_init rtp_kjnCHdFKRkNS
#define rc4_crypt rtp_LFPiktjcSlpH
#define parse_args rtp_TKYpQAMlqEEo
#define print_usage rtp_yPgDxXLkKChu

#endif // MUTATED_H
