#ifndef MUTATED_H
#define MUTATED_H

// Auto-generated by RTP GUI Builder
// Timestamp: 623752

#define rtp_init rtp_nnbKhlCLqjqR
#define rtp_run rtp_AAmnSQwFRcJN
#define rtp_cleanup rtp_kbNElqSfDBNJ
#define net_init rtp_GXtxrpdlsiNg
#define net_cleanup rtp_RZsIchfAHWZN
#define net_set_nonblocking rtp_DRzOUmhitQMb
#define net_listen rtp_QrZgrxDDiNYe
#define net_connect rtp_tOWdJEsGdxIK
#define rc4_init rtp_eIjiBdXEhaIp
#define rc4_crypt rtp_ojIjbiqgLkHd
#define parse_args rtp_uJurQvDmOmMJ
#define print_usage rtp_LObLHfsetRSA

#endif // MUTATED_H
